/* ─── Shared Team interface ─────────────────────────────────── */

export interface Team {
    code: string;
    name: string;
    location: string;
    color: string;
}

/** @deprecated Use Team instead */
export type NFLTeam = Team;

/* ─── NFL Teams ─────────────────────────────────────────────── */

export const nflTeams: Team[] = [
    { code: 'ARI', name: 'Cardinals', location: 'Arizona', color: '#97233F' },
    { code: 'ATL', name: 'Falcons', location: 'Atlanta', color: '#A71930' },
    { code: 'BAL', name: 'Ravens', location: 'Baltimore', color: '#241773' },
    { code: 'BUF', name: 'Bills', location: 'Buffalo', color: '#00338D' },
    { code: 'CAR', name: 'Panthers', location: 'Carolina', color: '#0085CA' },
    { code: 'CHI', name: 'Bears', location: 'Chicago', color: '#0B162A' },
    { code: 'CIN', name: 'Bengals', location: 'Cincinnati', color: '#FB4F14' },
    { code: 'CLE', name: 'Browns', location: 'Cleveland', color: '#311D00' },
    { code: 'DAL', name: 'Cowboys', location: 'Dallas', color: '#041E42' },
    { code: 'DEN', name: 'Broncos', location: 'Denver', color: '#FB4F14' },
    { code: 'DET', name: 'Lions', location: 'Detroit', color: '#0076B6' },
    { code: 'GB', name: 'Packers', location: 'Green Bay', color: '#203731' },
    { code: 'HOU', name: 'Texans', location: 'Houston', color: '#03202F' },
    { code: 'IND', name: 'Colts', location: 'Indianapolis', color: '#002C5F' },
    { code: 'JAX', name: 'Jaguars', location: 'Jacksonville', color: '#006778' },
    { code: 'KC', name: 'Chiefs', location: 'Kansas City', color: '#E31837' },
    { code: 'LV', name: 'Raiders', location: 'Las Vegas', color: '#000000' },
    { code: 'LAC', name: 'Chargers', location: 'Los Angeles', color: '#002A5E' },
    { code: 'LAR', name: 'Rams', location: 'Los Angeles', color: '#002244' },
    { code: 'MIA', name: 'Dolphins', location: 'Miami', color: '#008E97' },
    { code: 'MIN', name: 'Vikings', location: 'Minnesota', color: '#4F2683' },
    { code: 'NE', name: 'Patriots', location: 'New England', color: '#002244' },
    { code: 'NO', name: 'Saints', location: 'New Orleans', color: '#D3BC8D' },
    { code: 'NYG', name: 'Giants', location: 'New York', color: '#0B2265' },
    { code: 'NYJ', name: 'Jets', location: 'New York', color: '#203731' },
    { code: 'PHI', name: 'Eagles', location: 'Philadelphia', color: '#004C54' },
    { code: 'PIT', name: 'Steelers', location: 'Pittsburgh', color: '#FFB612' },
    { code: 'SF', name: '49ers', location: 'San Francisco', color: '#AA0000' },
    { code: 'SEA', name: 'Seahawks', location: 'Seattle', color: '#002244' },
    { code: 'TB', name: 'Buccaneers', location: 'Tampa Bay', color: '#D50A0A' },
    { code: 'TEN', name: 'Titans', location: 'Tennessee', color: '#0C2340' },
    { code: 'WAS', name: 'Commanders', location: 'Washington', color: '#773141' },
];

/* ─── NCAA Basketball Teams (Division I) ────────────────────── */

export const ncaabTeams: Team[] = [
    // A
    { code: 'ACU', name: 'Wildcats', location: 'Abilene Christian', color: '#461D7C' },
    { code: 'AF', name: 'Falcons', location: 'Air Force', color: '#003087' },
    { code: 'AKR', name: 'Zips', location: 'Akron', color: '#041E42' },
    { code: 'AAMU', name: 'Bulldogs', location: 'Alabama A&M', color: '#660000' },
    { code: 'BAMA', name: 'Crimson Tide', location: 'Alabama', color: '#9E1B32' },
    { code: 'ALST', name: 'Hornets', location: 'Alabama State', color: '#D2A441' },
    { code: 'ALB', name: 'Great Danes', location: 'Albany', color: '#461D7C' },
    { code: 'ALCN', name: 'Braves', location: 'Alcorn State', color: '#461D7C' },
    { code: 'AMER', name: 'Eagles', location: 'American', color: '#CC0000' },
    { code: 'APP', name: 'Mountaineers', location: 'Appalachian State', color: '#222222' },
    { code: 'ARIZ', name: 'Wildcats', location: 'Arizona', color: '#CC0033' },
    { code: 'ASU', name: 'Sun Devils', location: 'Arizona State', color: '#8C1D40' },
    { code: 'ARK', name: 'Razorbacks', location: 'Arkansas', color: '#9D2235' },
    { code: 'ARST', name: 'Red Wolves', location: 'Arkansas State', color: '#CC092F' },
    { code: 'ARPB', name: 'Golden Lions', location: 'Arkansas-Pine Bluff', color: '#EEB211' },
    { code: 'ARMY', name: 'Black Knights', location: 'Army', color: '#000000' },
    { code: 'AUB', name: 'Tigers', location: 'Auburn', color: '#0C2340' },
    { code: 'APSU', name: 'Governors', location: 'Austin Peay', color: '#C41E3A' },

    // B
    { code: 'BALL', name: 'Cardinals', location: 'Ball State', color: '#BA0C2F' },
    { code: 'BAY', name: 'Bears', location: 'Baylor', color: '#003015' },
    { code: 'BELL', name: 'Bruins', location: 'Bellarmine', color: '#C41230' },
    { code: 'BELM', name: 'Bruins', location: 'Belmont', color: '#002469' },
    { code: 'BCU', name: 'Wildcats', location: 'Bethune-Cookman', color: '#660000' },
    { code: 'BING', name: 'Bearcats', location: 'Binghamton', color: '#005A43' },
    { code: 'BSU', name: 'Broncos', location: 'Boise State', color: '#0033A0' },
    { code: 'BC', name: 'Eagles', location: 'Boston College', color: '#8B2332' },
    { code: 'BU', name: 'Terriers', location: 'Boston University', color: '#CC0000' },
    { code: 'BGSU', name: 'Falcons', location: 'Bowling Green', color: '#FF7300' },
    { code: 'BRAD', name: 'Braves', location: 'Bradley', color: '#C41230' },
    { code: 'BRWN', name: 'Bears', location: 'Brown', color: '#4E3629' },
    { code: 'BRYT', name: 'Bulldogs', location: 'Bryant', color: '#000000' },
    { code: 'BUCK', name: 'Bison', location: 'Bucknell', color: '#E87722' },
    { code: 'BUFF', name: 'Bulls', location: 'Buffalo', color: '#005BBB' },
    { code: 'BUTL', name: 'Bulldogs', location: 'Butler', color: '#13294B' },
    { code: 'BYU', name: 'Cougars', location: 'BYU', color: '#002E5D' },

    // C
    { code: 'CAL', name: 'Golden Bears', location: 'California', color: '#003262' },
    { code: 'CBU', name: 'Lancers', location: 'Cal Baptist', color: '#002855' },
    { code: 'CP', name: 'Mustangs', location: 'Cal Poly', color: '#1F4F2B' },
    { code: 'CSUF', name: 'Titans', location: 'Cal State Fullerton', color: '#00274C' },
    { code: 'CSUB', name: 'Roadrunners', location: 'Cal State Bakersfield', color: '#003DA5' },
    { code: 'CSUN', name: 'Matadors', location: 'Cal State Northridge', color: '#CE1126' },
    { code: 'CAMP', name: 'Camels', location: 'Campbell', color: '#F47920' },
    { code: 'CAN', name: 'Golden Griffins', location: 'Canisius', color: '#003DA5' },
    { code: 'CARB', name: 'Bears', location: 'Central Arkansas', color: '#4F2D7F' },
    { code: 'CCSU', name: 'Blue Devils', location: 'Central Connecticut', color: '#003DA5' },
    { code: 'CMU', name: 'Chippewas', location: 'Central Michigan', color: '#6A0032' },
    { code: 'CHRL', name: '49ers', location: 'Charlotte', color: '#005035' },
    { code: 'CHSO', name: 'Buccaneers', location: 'Charleston Southern', color: '#003DA5' },
    { code: 'COFC', name: 'Cougars', location: 'Charleston', color: '#800000' },
    { code: 'CHAT', name: 'Mocs', location: 'Chattanooga', color: '#00386B' },
    { code: 'CIN', name: 'Bearcats', location: 'Cincinnati', color: '#E00122' },
    { code: 'CIT', name: 'Bulldogs', location: 'The Citadel', color: '#009CDE' },
    { code: 'CLEM', name: 'Tigers', location: 'Clemson', color: '#F56600' },
    { code: 'CLEV', name: 'Vikings', location: 'Cleveland State', color: '#006747' },
    { code: 'CCU', name: 'Chanticleers', location: 'Coastal Carolina', color: '#006F71' },
    { code: 'COLG', name: 'Raiders', location: 'Colgate', color: '#821019' },
    { code: 'COLO', name: 'Buffaloes', location: 'Colorado', color: '#CFB87C' },
    { code: 'CSU', name: 'Rams', location: 'Colorado State', color: '#1E4D2B' },
    { code: 'COL', name: 'Lions', location: 'Columbia', color: '#9BCBEB' },
    { code: 'CONN', name: 'Huskies', location: 'Connecticut', color: '#000E2F' },
    { code: 'COPP', name: 'Eagles', location: 'Coppin State', color: '#C8102E' },
    { code: 'CORN', name: 'Big Red', location: 'Cornell', color: '#B31B1B' },
    { code: 'CREI', name: 'Bluejays', location: 'Creighton', color: '#005CA9' },

    // D
    { code: 'DART', name: 'Big Green', location: 'Dartmouth', color: '#00693E' },
    { code: 'DAV', name: 'Wildcats', location: 'Davidson', color: '#CC0000' },
    { code: 'DAY', name: 'Flyers', location: 'Dayton', color: '#CE1141' },
    { code: 'DEL', name: 'Blue Hens', location: 'Delaware', color: '#00539F' },
    { code: 'DSU', name: 'Hornets', location: 'Delaware State', color: '#C41230' },
    { code: 'DEN', name: 'Pioneers', location: 'Denver', color: '#8B2332' },
    { code: 'DEP', name: 'Blue Demons', location: 'DePaul', color: '#005EB8' },
    { code: 'DET', name: 'Titans', location: 'Detroit Mercy', color: '#C41230' },
    { code: 'DRKE', name: 'Bulldogs', location: 'Drake', color: '#004477' },
    { code: 'DREX', name: 'Dragons', location: 'Drexel', color: '#07294D' },
    { code: 'DUKE', name: 'Blue Devils', location: 'Duke', color: '#003087' },
    { code: 'DUQ', name: 'Dukes', location: 'Duquesne', color: '#002D72' },

    // E
    { code: 'ECU', name: 'Pirates', location: 'East Carolina', color: '#592A8A' },
    { code: 'EIU', name: 'Panthers', location: 'Eastern Illinois', color: '#004B83' },
    { code: 'EKU', name: 'Colonels', location: 'Eastern Kentucky', color: '#861F41' },
    { code: 'EMU', name: 'Eagles', location: 'Eastern Michigan', color: '#006747' },
    { code: 'EWU', name: 'Eagles', location: 'Eastern Washington', color: '#A10022' },
    { code: 'ELON', name: 'Phoenix', location: 'Elon', color: '#730023' },
    { code: 'ETSU', name: 'Buccaneers', location: 'East Tennessee State', color: '#041E42' },
    { code: 'EVAN', name: 'Purple Aces', location: 'Evansville', color: '#461D7C' },

    // F
    { code: 'FAIR', name: 'Stags', location: 'Fairfield', color: '#CC0000' },
    { code: 'FDU', name: 'Knights', location: 'Fairleigh Dickinson', color: '#003DA5' },
    { code: 'FAMU', name: 'Rattlers', location: 'Florida A&M', color: '#F47920' },
    { code: 'FAU', name: 'Owls', location: 'Florida Atlantic', color: '#003366' },
    { code: 'FLA', name: 'Gators', location: 'Florida', color: '#0021A5' },
    { code: 'FGCU', name: 'Eagles', location: 'Florida Gulf Coast', color: '#002F6C' },
    { code: 'FIU', name: 'Panthers', location: 'Florida International', color: '#002F6C' },
    { code: 'FSU', name: 'Seminoles', location: 'Florida State', color: '#782F40' },
    { code: 'FORD', name: 'Rams', location: 'Fordham', color: '#8B0029' },
    { code: 'FRES', name: 'Bulldogs', location: 'Fresno State', color: '#CC0000' },
    { code: 'FUR', name: 'Paladins', location: 'Furman', color: '#582C83' },

    // G
    { code: 'GW', name: 'Colonials', location: 'George Washington', color: '#002654' },
    { code: 'GMU', name: 'Patriots', location: 'George Mason', color: '#006633' },
    { code: 'GTWN', name: 'Hoyas', location: 'Georgetown', color: '#041E42' },
    { code: 'UGA', name: 'Bulldogs', location: 'Georgia', color: '#BA0C2F' },
    { code: 'GASO', name: 'Eagles', location: 'Georgia Southern', color: '#041E42' },
    { code: 'GAST', name: 'Panthers', location: 'Georgia State', color: '#0039A6' },
    { code: 'GT', name: 'Yellow Jackets', location: 'Georgia Tech', color: '#B3A369' },
    { code: 'GONZ', name: 'Bulldogs', location: 'Gonzaga', color: '#002967' },
    { code: 'GRAM', name: 'Tigers', location: 'Grambling State', color: '#000000' },
    { code: 'GCU', name: 'Antelopes', location: 'Grand Canyon', color: '#522D80' },
    { code: 'GBY', name: 'Phoenix', location: 'Green Bay', color: '#006747' },
    { code: 'GWU', name: 'Bulldogs', location: 'Gardner-Webb', color: '#B3131A' },

    // H
    { code: 'HAMP', name: 'Pirates', location: 'Hampton', color: '#003DA5' },
    { code: 'HARV', name: 'Crimson', location: 'Harvard', color: '#A51C30' },
    { code: 'HAW', name: 'Rainbow Warriors', location: "Hawai'i", color: '#024731' },
    { code: 'HIPO', name: 'Panthers', location: 'High Point', color: '#330072' },
    { code: 'HOF', name: 'Pride', location: 'Hofstra', color: '#003591' },
    { code: 'HC', name: 'Crusaders', location: 'Holy Cross', color: '#602D89' },
    { code: 'HOU', name: 'Cougars', location: 'Houston', color: '#C8102E' },
    { code: 'HCU', name: 'Huskies', location: 'Houston Christian', color: '#F68B1F' },
    { code: 'HOW', name: 'Bison', location: 'Howard', color: '#003DA5' },

    // I
    { code: 'IDHO', name: 'Vandals', location: 'Idaho', color: '#B5985A' },
    { code: 'IDST', name: 'Bengals', location: 'Idaho State', color: '#F47920' },
    { code: 'ILL', name: 'Fighting Illini', location: 'Illinois', color: '#E84A27' },
    { code: 'ILST', name: 'Redbirds', location: 'Illinois State', color: '#CE1126' },
    { code: 'IW', name: 'Cardinals', location: 'Incarnate Word', color: '#CE1126' },
    { code: 'IND', name: 'Hoosiers', location: 'Indiana', color: '#990000' },
    { code: 'INST', name: 'Sycamores', location: 'Indiana State', color: '#00669A' },
    { code: 'IONA', name: 'Gaels', location: 'Iona', color: '#6A0032' },
    { code: 'IOWA', name: 'Hawkeyes', location: 'Iowa', color: '#FFCD00' },
    { code: 'ISU', name: 'Cyclones', location: 'Iowa State', color: '#C8102E' },

    // J
    { code: 'JKST', name: 'Tigers', location: 'Jackson State', color: '#002D62' },
    { code: 'JAX', name: 'Dolphins', location: 'Jacksonville', color: '#006747' },
    { code: 'JXST', name: 'Gamecocks', location: 'Jacksonville State', color: '#CC0000' },
    { code: 'JMU', name: 'Dukes', location: 'James Madison', color: '#450084' },

    // K
    { code: 'KU', name: 'Jayhawks', location: 'Kansas', color: '#0051BA' },
    { code: 'KSU', name: 'Wildcats', location: 'Kansas State', color: '#512888' },
    { code: 'KNST', name: 'Owls', location: 'Kennesaw State', color: '#FDBB30' },
    { code: 'KENT', name: 'Golden Flashes', location: 'Kent State', color: '#002664' },
    { code: 'UK', name: 'Wildcats', location: 'Kentucky', color: '#0033A0' },

    // L
    { code: 'LAF', name: 'Leopards', location: 'Lafayette', color: '#8B0029' },
    { code: 'LAM', name: 'Cardinals', location: 'Lamar', color: '#C41230' },
    { code: 'LAS', name: 'Explorers', location: 'La Salle', color: '#002855' },
    { code: 'LEH', name: 'Mountain Hawks', location: 'Lehigh', color: '#653600' },
    { code: 'LIB', name: 'Flames', location: 'Liberty', color: '#002D62' },
    { code: 'LIPS', name: 'Bisons', location: 'Lipscomb', color: '#461D7C' },
    { code: 'LBSU', name: '49ers', location: 'Long Beach State', color: '#000000' },
    { code: 'LIU', name: 'Sharks', location: 'Long Island', color: '#005DAA' },
    { code: 'LONG', name: 'Lancers', location: 'Longwood', color: '#003DA5' },
    { code: 'ULL', name: "Ragin' Cajuns", location: 'Louisiana', color: '#CE181E' },
    { code: 'ULM', name: 'Warhawks', location: 'Louisiana-Monroe', color: '#800029' },
    { code: 'LSU', name: 'Tigers', location: 'LSU', color: '#461D7C' },
    { code: 'LAT', name: 'Bulldogs', location: 'Louisiana Tech', color: '#002F8B' },
    { code: 'LOU', name: 'Cardinals', location: 'Louisville', color: '#AD0000' },
    { code: 'LMU', name: 'Lions', location: 'Loyola Marymount', color: '#003DA5' },
    { code: 'LOMD', name: 'Greyhounds', location: 'Loyola (MD)', color: '#006747' },
    { code: 'LCHI', name: 'Ramblers', location: 'Loyola Chicago', color: '#800029' },

    // M
    { code: 'ME', name: 'Black Bears', location: 'Maine', color: '#003263' },
    { code: 'MAN', name: 'Jaspers', location: 'Manhattan', color: '#006747' },
    { code: 'MRST', name: 'Red Foxes', location: 'Marist', color: '#C8102E' },
    { code: 'MARQ', name: 'Golden Eagles', location: 'Marquette', color: '#003DA5' },
    { code: 'MRSH', name: 'Thundering Herd', location: 'Marshall', color: '#00B140' },
    { code: 'UMD', name: 'Terrapins', location: 'Maryland', color: '#E03A3E' },
    { code: 'UMES', name: 'Hawks', location: 'Maryland-Eastern Shore', color: '#C8102E' },
    { code: 'MASS', name: 'Minutemen', location: 'Massachusetts', color: '#881C1C' },
    { code: 'MCNS', name: 'Cowboys', location: 'McNeese', color: '#003DA5' },
    { code: 'MEM', name: 'Tigers', location: 'Memphis', color: '#003DA5' },
    { code: 'MERC', name: 'Bears', location: 'Mercer', color: '#F47920' },
    { code: 'MRMK', name: 'Warriors', location: 'Merrimack', color: '#003DA5' },
    { code: 'MIAF', name: 'Hurricanes', location: 'Miami (FL)', color: '#F47321' },
    { code: 'MIAO', name: 'RedHawks', location: 'Miami (OH)', color: '#C3142D' },
    { code: 'MICH', name: 'Wolverines', location: 'Michigan', color: '#00274C' },
    { code: 'MSU', name: 'Spartans', location: 'Michigan State', color: '#18453B' },
    { code: 'MTSU', name: 'Blue Raiders', location: 'Middle Tennessee', color: '#0066CC' },
    { code: 'MIL', name: 'Panthers', location: 'Milwaukee', color: '#000000' },
    { code: 'MINN', name: 'Golden Gophers', location: 'Minnesota', color: '#7A0019' },
    { code: 'MSST', name: 'Bulldogs', location: 'Mississippi State', color: '#660000' },
    { code: 'MISS', name: 'Rebels', location: 'Ole Miss', color: '#14213D' },
    { code: 'MIZ', name: 'Tigers', location: 'Missouri', color: '#F1B82D' },
    { code: 'MOST', name: 'Bears', location: 'Missouri State', color: '#8B0029' },
    { code: 'MVSU', name: 'Delta Devils', location: 'Mississippi Valley State', color: '#006747' },
    { code: 'MON', name: 'Grizzlies', location: 'Montana', color: '#6C4023' },
    { code: 'MNST', name: 'Bobcats', location: 'Montana State', color: '#003DA5' },
    { code: 'MONM', name: 'Hawks', location: 'Monmouth', color: '#003DA5' },
    { code: 'MOSU', name: 'Eagles', location: 'Morehead State', color: '#003DA5' },
    { code: 'MORG', name: 'Bears', location: 'Morgan State', color: '#F47920' },
    { code: 'MURR', name: 'Racers', location: 'Murray State', color: '#002144' },

    // N
    { code: 'NAVY', name: 'Midshipmen', location: 'Navy', color: '#00205B' },
    { code: 'NEB', name: 'Cornhuskers', location: 'Nebraska', color: '#E41C38' },
    { code: 'NEV', name: 'Wolf Pack', location: 'Nevada', color: '#003366' },
    { code: 'UNLV', name: 'Rebels', location: 'UNLV', color: '#CF0A2C' },
    { code: 'UNH', name: 'Wildcats', location: 'New Hampshire', color: '#003DA5' },
    { code: 'UNM', name: 'Lobos', location: 'New Mexico', color: '#BA0C2F' },
    { code: 'NMSU', name: 'Aggies', location: 'New Mexico State', color: '#8B0029' },
    { code: 'UNO', name: 'Privateers', location: 'New Orleans', color: '#003366' },
    { code: 'NIAG', name: 'Purple Eagles', location: 'Niagara', color: '#461D7C' },
    { code: 'NICH', name: 'Colonels', location: 'Nicholls', color: '#C8102E' },
    { code: 'NJIT', name: 'Highlanders', location: 'NJIT', color: '#CE1126' },
    { code: 'NCAT', name: 'Aggies', location: 'North Carolina A&T', color: '#004684' },
    { code: 'NCCU', name: 'Eagles', location: 'NC Central', color: '#862633' },
    { code: 'UNC', name: 'Tar Heels', location: 'North Carolina', color: '#7BAFD4' },
    { code: 'NCST', name: 'Wolfpack', location: 'NC State', color: '#CC0000' },
    { code: 'UND', name: 'Fighting Hawks', location: 'North Dakota', color: '#009A44' },
    { code: 'NDST', name: 'Bison', location: 'North Dakota State', color: '#006A31' },
    { code: 'NEU', name: 'Huskies', location: 'Northeastern', color: '#D41B2C' },
    { code: 'NAU', name: 'Lumberjacks', location: 'Northern Arizona', color: '#003466' },
    { code: 'UNCO', name: 'Bears', location: 'Northern Colorado', color: '#003DA5' },
    { code: 'NIU', name: 'Huskies', location: 'Northern Illinois', color: '#BA0C2F' },
    { code: 'UNI', name: 'Panthers', location: 'Northern Iowa', color: '#4B116F' },
    { code: 'NKU', name: 'Norse', location: 'Northern Kentucky', color: '#000000' },
    { code: 'UNF', name: 'Ospreys', location: 'North Florida', color: '#003DA5' },
    { code: 'UNT', name: 'Mean Green', location: 'North Texas', color: '#00853E' },
    { code: 'NW', name: 'Wildcats', location: 'Northwestern', color: '#4E2A84' },
    { code: 'NWST', name: 'Demons', location: 'Northwestern State', color: '#461D7C' },
    { code: 'ND', name: 'Fighting Irish', location: 'Notre Dame', color: '#0C2340' },
    { code: 'NALA', name: 'Lions', location: 'North Alabama', color: '#461D7C' },

    // O
    { code: 'OAK', name: 'Golden Grizzlies', location: 'Oakland', color: '#B89B59' },
    { code: 'OHIO', name: 'Bobcats', location: 'Ohio', color: '#00694E' },
    { code: 'OSU', name: 'Buckeyes', location: 'Ohio State', color: '#BB0000' },
    { code: 'OU', name: 'Sooners', location: 'Oklahoma', color: '#841617' },
    { code: 'OKST', name: 'Cowboys', location: 'Oklahoma State', color: '#FF7300' },
    { code: 'ODU', name: 'Monarchs', location: 'Old Dominion', color: '#003057' },
    { code: 'OMA', name: 'Mavericks', location: 'Omaha', color: '#000000' },
    { code: 'ORU', name: 'Golden Eagles', location: 'Oral Roberts', color: '#002F6C' },
    { code: 'ORE', name: 'Ducks', location: 'Oregon', color: '#154733' },
    { code: 'ORST', name: 'Beavers', location: 'Oregon State', color: '#DC4405' },

    // P
    { code: 'PAC', name: 'Tigers', location: 'Pacific', color: '#F47920' },
    { code: 'PENN', name: 'Quakers', location: 'Penn', color: '#011F5B' },
    { code: 'PSU', name: 'Nittany Lions', location: 'Penn State', color: '#041E42' },
    { code: 'PEPP', name: 'Waves', location: 'Pepperdine', color: '#00205B' },
    { code: 'PITT', name: 'Panthers', location: 'Pittsburgh', color: '#003594' },
    { code: 'PORT', name: 'Pilots', location: 'Portland', color: '#461D7C' },
    { code: 'PTST', name: 'Vikings', location: 'Portland State', color: '#154733' },
    { code: 'PVAM', name: 'Panthers', location: 'Prairie View A&M', color: '#461D7C' },
    { code: 'PRES', name: 'Blue Hose', location: 'Presbyterian', color: '#003DA5' },
    { code: 'PRIN', name: 'Tigers', location: 'Princeton', color: '#E77500' },
    { code: 'PROV', name: 'Friars', location: 'Providence', color: '#000000' },
    { code: 'PUR', name: 'Boilermakers', location: 'Purdue', color: '#CEB888' },

    // Q
    { code: 'QUIN', name: 'Bobcats', location: 'Quinnipiac', color: '#002D62' },

    // R
    { code: 'RAD', name: 'Highlanders', location: 'Radford', color: '#CC0000' },
    { code: 'URI', name: 'Rams', location: 'Rhode Island', color: '#002B5C' },
    { code: 'RICE', name: 'Owls', location: 'Rice', color: '#002469' },
    { code: 'RICH', name: 'Spiders', location: 'Richmond', color: '#990000' },
    { code: 'RID', name: 'Broncs', location: 'Rider', color: '#8B0029' },
    { code: 'RUT', name: 'Scarlet Knights', location: 'Rutgers', color: '#CC0033' },

    // S
    { code: 'SAC', name: 'Hornets', location: 'Sacramento State', color: '#043927' },
    { code: 'SHU', name: 'Pirates', location: 'Seton Hall', color: '#003DA5' },
    { code: 'SAM', name: 'Bearkats', location: 'Sam Houston', color: '#F47920' },
    { code: 'SDSU', name: 'Aztecs', location: 'San Diego State', color: '#A6192E' },
    { code: 'USD', name: 'Toreros', location: 'San Diego', color: '#002855' },
    { code: 'SFPA', name: 'Dons', location: 'San Francisco', color: '#006747' },
    { code: 'SJSU', name: 'Spartans', location: 'San Jose State', color: '#0055A2' },
    { code: 'SCU', name: 'Broncos', location: 'Santa Clara', color: '#862633' },
    { code: 'SAV', name: 'Tigers', location: 'Savannah State', color: '#002855' },
    { code: 'SEA', name: 'Redhawks', location: 'Seattle', color: '#AA0000' },
    { code: 'SIE', name: 'Saints', location: 'Siena', color: '#006747' },
    { code: 'SIU', name: 'Salukis', location: 'Southern Illinois', color: '#720000' },
    { code: 'SIUE', name: 'Cougars', location: 'SIU Edwardsville', color: '#CC0000' },
    { code: 'SMU', name: 'Mustangs', location: 'SMU', color: '#CC0000' },
    { code: 'SC', name: 'Gamecocks', location: 'South Carolina', color: '#73000A' },
    { code: 'SCST', name: 'Bulldogs', location: 'South Carolina State', color: '#800029' },
    { code: 'SCUP', name: 'Paladins', location: 'SC Upstate', color: '#006747' },
    { code: 'USD2', name: 'Coyotes', location: 'South Dakota', color: '#CD1241' },
    { code: 'SDST', name: 'Jackrabbits', location: 'South Dakota State', color: '#0033A0' },
    { code: 'SEL', name: 'Lions', location: 'Southeastern Louisiana', color: '#006747' },
    { code: 'SEMO', name: 'Redhawks', location: 'Southeast Missouri State', color: '#C8102E' },
    { code: 'SOUM', name: 'Jaguars', location: 'Southern', color: '#003DA5' },
    { code: 'SMISS', name: 'Golden Eagles', location: 'Southern Miss', color: '#FFB81C' },
    { code: 'SOU', name: 'Bulldogs', location: 'Southern Utah', color: '#CC0000' },
    { code: 'STBK', name: 'Seawolves', location: 'Stony Brook', color: '#990000' },
    { code: 'SFA', name: 'Lumberjacks', location: 'Stephen F. Austin', color: '#3E2680' },
    { code: 'STET', name: 'Hatters', location: 'Stetson', color: '#006747' },
    { code: 'STMR', name: "Bobcats", location: "St. Thomas (MN)", color: '#461D7C' },
    { code: 'SJU', name: "Red Storm", location: "St. John's", color: '#CC0000' },
    { code: 'SJOE', name: "Hawks", location: "Saint Joseph's", color: '#9E1B32' },
    { code: 'SLU', name: 'Billikens', location: 'Saint Louis', color: '#003DA5' },
    { code: 'SMRY', name: "Gaels", location: "Saint Mary's", color: '#003DA5' },
    { code: 'SPU', name: "Bonnies", location: "St. Bonaventure", color: '#7B3F00' },
    { code: 'STFR', name: 'Red Flash', location: "Saint Francis", color: '#CC0000' },
    { code: 'SFNY', name: 'Terriers', location: "St. Francis Brooklyn", color: '#003DA5' },
    { code: 'SPE', name: 'Peacocks', location: "Saint Peter's", color: '#003DA5' },
    { code: 'STAN', name: 'Cardinal', location: 'Stanford', color: '#8C1515' },
    { code: 'SYR', name: 'Orange', location: 'Syracuse', color: '#D44500' },

    // T
    { code: 'TCU', name: 'Horned Frogs', location: 'TCU', color: '#4D1979' },
    { code: 'TEM', name: 'Owls', location: 'Temple', color: '#9D2235' },
    { code: 'TENN', name: 'Volunteers', location: 'Tennessee', color: '#FF8200' },
    { code: 'TNST', name: 'Tigers', location: 'Tennessee State', color: '#003DA5' },
    { code: 'TNMC', name: 'Skyhawks', location: 'Tennessee-Martin', color: '#F47920' },
    { code: 'TNTH', name: 'Golden Eagles', location: 'Tennessee Tech', color: '#461D7C' },
    { code: 'TEX', name: 'Longhorns', location: 'Texas', color: '#BF5700' },
    { code: 'TAMU', name: 'Aggies', location: 'Texas A&M', color: '#500000' },
    { code: 'TAMC', name: 'Islanders', location: 'Texas A&M-Corpus Christi', color: '#0067C5' },
    { code: 'TXSO', name: 'Tigers', location: 'Texas Southern', color: '#800029' },
    { code: 'TXST', name: 'Bobcats', location: 'Texas State', color: '#501214' },
    { code: 'TTU', name: 'Red Raiders', location: 'Texas Tech', color: '#CC0000' },
    { code: 'TAR', name: 'Texans', location: 'Tarleton State', color: '#461D7C' },
    { code: 'TOL', name: 'Rockets', location: 'Toledo', color: '#003366' },
    { code: 'TOW', name: 'Tigers', location: 'Towson', color: '#FFB81C' },
    { code: 'TROY', name: 'Trojans', location: 'Troy', color: '#8B0029' },
    { code: 'TUL', name: 'Golden Hurricane', location: 'Tulsa', color: '#003366' },
    { code: 'TULN', name: 'Green Wave', location: 'Tulane', color: '#006747' },

    // U
    { code: 'UCF', name: 'Knights', location: 'UCF', color: '#BA9B37' },
    { code: 'UCLA', name: 'Bruins', location: 'UCLA', color: '#2D68C4' },
    { code: 'UCSB', name: 'Gauchos', location: 'UC Santa Barbara', color: '#003660' },
    { code: 'UCD', name: 'Aggies', location: 'UC Davis', color: '#002855' },
    { code: 'UCI', name: 'Anteaters', location: 'UC Irvine', color: '#0064A4' },
    { code: 'UCR', name: 'Highlanders', location: 'UC Riverside', color: '#003DA5' },
    { code: 'UCSD', name: 'Tritons', location: 'UC San Diego', color: '#003B5C' },
    { code: 'UTAH', name: 'Utes', location: 'Utah', color: '#CC0000' },
    { code: 'USU', name: 'Aggies', location: 'Utah State', color: '#0F2439' },
    { code: 'UVU', name: 'Wolverines', location: 'Utah Valley', color: '#275D38' },
    { code: 'UTEP', name: 'Miners', location: 'UTEP', color: '#FF8200' },
    { code: 'UTSA', name: 'Roadrunners', location: 'UTSA', color: '#0C2340' },
    { code: 'UTRI', name: 'Spartans', location: 'UT Rio Grande Valley', color: '#F47920' },

    // V
    { code: 'VALE', name: 'Blazers', location: 'Valparaiso', color: '#613318' },
    { code: 'VAN', name: 'Commodores', location: 'Vanderbilt', color: '#B3A369' },
    { code: 'VCU', name: 'Rams', location: 'VCU', color: '#000000' },
    { code: 'VERM', name: 'Catamounts', location: 'Vermont', color: '#005710' },
    { code: 'VILL', name: 'Wildcats', location: 'Villanova', color: '#003366' },
    { code: 'UVA', name: 'Cavaliers', location: 'Virginia', color: '#232D4B' },
    { code: 'VMI', name: 'Keydets', location: 'VMI', color: '#CC0000' },
    { code: 'VT', name: 'Hokies', location: 'Virginia Tech', color: '#660000' },

    // W
    { code: 'WAKE', name: 'Demon Deacons', location: 'Wake Forest', color: '#9E7E38' },
    { code: 'WASH', name: 'Huskies', location: 'Washington', color: '#4B2E83' },
    { code: 'WSU', name: 'Cougars', location: 'Washington State', color: '#981E32' },
    { code: 'WEB', name: 'Wildcats', location: 'Weber State', color: '#4B2682' },
    { code: 'WVU', name: 'Mountaineers', location: 'West Virginia', color: '#002855' },
    { code: 'WKU', name: 'Hilltoppers', location: 'Western Kentucky', color: '#C60C30' },
    { code: 'WMU', name: 'Broncos', location: 'Western Michigan', color: '#6C4023' },
    { code: 'WCU', name: 'Catamounts', location: 'Western Carolina', color: '#592A8A' },
    { code: 'WIU', name: 'Leathernecks', location: 'Western Illinois', color: '#461D7C' },
    { code: 'WIS', name: 'Badgers', location: 'Wisconsin', color: '#C5050C' },
    { code: 'W&M', name: 'Tribe', location: 'William & Mary', color: '#115740' },
    { code: 'WINT', name: 'Eagles', location: 'Winthrop', color: '#862633' },
    { code: 'WOF', name: 'Terriers', location: 'Wofford', color: '#886B2C' },
    { code: 'WRST', name: 'Raiders', location: 'Wright State', color: '#007A33' },
    { code: 'WYO', name: 'Cowboys', location: 'Wyoming', color: '#492F24' },

    // X-Y-Z
    { code: 'XAV', name: 'Musketeers', location: 'Xavier', color: '#002D72' },
    { code: 'YALE', name: 'Bulldogs', location: 'Yale', color: '#0F4D92' },
    { code: 'YSU', name: 'Penguins', location: 'Youngstown State', color: '#C8102E' },
];
