export const nflTeams = [
    { code: 'ARI', name: 'Cardinals', location: 'Arizona', color: '#97233F' },
    { code: 'ATL', name: 'Falcons', location: 'Atlanta', color: '#A71930' },
    { code: 'BAL', name: 'Ravens', location: 'Baltimore', color: '#241773' },
    { code: 'BUF', name: 'Bills', location: 'Buffalo', color: '#00338D' },
    { code: 'CAR', name: 'Panthers', location: 'Carolina', color: '#0085CA' },
    { code: 'CHI', name: 'Bears', location: 'Chicago', color: '#0B162A' },
    { code: 'CIN', name: 'Bengals', location: 'Cincinnati', color: '#FB4F14' },
    { code: 'CLE', name: 'Browns', location: 'Cleveland', color: '#311D00' },
    { code: 'DAL', name: 'Cowboys', location: 'Dallas', color: '#041E42' },
    { code: 'DEN', name: 'Broncos', location: 'Denver', color: '#FB4F14' },
    { code: 'DET', name: 'Lions', location: 'Detroit', color: '#0076B6' },
    { code: 'GB', name: 'Packers', location: 'Green Bay', color: '#203731' },
    { code: 'HOU', name: 'Texans', location: 'Houston', color: '#03202F' },
    { code: 'IND', name: 'Colts', location: 'Indianapolis', color: '#002C5F' },
    { code: 'JAX', name: 'Jaguars', location: 'Jacksonville', color: '#006778' },
    { code: 'KC', name: 'Chiefs', location: 'Kansas City', color: '#E31837', default: 'horizontal' },
    { code: 'LV', name: 'Raiders', location: 'Las Vegas', color: '#000000' },
    { code: 'LAC', name: 'Chargers', location: 'Los Angeles', color: '#002A5E' },
    { code: 'LAR', name: 'Rams', location: 'Los Angeles', color: '#002244' },
    { code: 'MIA', name: 'Dolphins', location: 'Miami', color: '#008E97' },
    { code: 'MIN', name: 'Vikings', location: 'Minnesota', color: '#4F2683' },
    { code: 'NE', name: 'Patriots', location: 'New England', color: '#002244' },
    { code: 'NO', name: 'Saints', location: 'New Orleans', color: '#D3BC8D' },
    { code: 'NYG', name: 'Giants', location: 'New York', color: '#0B2265' },
    { code: 'NYJ', name: 'Jets', location: 'New York', color: '#203731' },
    { code: 'PHI', name: 'Eagles', location: 'Philadelphia', color: '#004C54' },
    { code: 'PIT', name: 'Steelers', location: 'Pittsburgh', color: '#FFB612' },
    { code: 'SF', name: '49ers', location: 'San Francisco', color: '#AA0000', default: 'vertical' },
    { code: 'SEA', name: 'Seahawks', location: 'Seattle', color: '#002244' },
    { code: 'TB', name: 'Buccaneers', location: 'Tampa Bay', color: '#D50A0A' },
    { code: 'TEN', name: 'Titans', location: 'Tennessee', color: '#0C2340' },
    { code: 'WAS', name: 'Commanders', location: 'Washington', color: '#773141' },
];
